server {
    listen 8080;

    root /usr/share/nginx/html;
    index index.html;

    # Proxy para o backend FastAPI
    resolver kube-dns.kube-system.svc.cluster.local valid=10s;
    set $backend http://proposta-api.site-orcamentos.svc.cluster.local:8000;

    location /api/ {
        proxy_pass $backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # SPA fallback — todas as rotas vão para index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
