[Interface]
Address = 10.10.0.1/24
ListenPort = 51820
PrivateKey = <SERVER_PRIVATE_KEY>

PostUp   = iptables -A FORWARD -i wg0 -o ens18 -j ACCEPT; iptables -A FORWARD -i ens18 -o wg0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT; iptables -t nat -A POSTROUTING -s 10.10.0.0/24 -o ens18 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -o ens18 -j ACCEPT; iptables -D FORWARD -i ens18 -o wg0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT; iptables -t nat -D POSTROUTING -s 10.10.0.0/24 -o ens18 -j MASQUERADE

[Peer]
PublicKey = hwMnnqCAqzGLsliRyKlgd5xPKlVKE9B8hA7YKXobcFg=
AllowedIPs = 10.10.0.2/32

[Peer]
PublicKey = TSPFZURLZOl/nP9RvBBD62xjG89qidfDRVqlsGtAcXo=
AllowedIPs = 10.10.0.3/32

[Peer]
PublicKey = c/a0Px7v7q3k5AGkOv2CrunLmK0zcHuj+bptsJ3m4hc=
AllowedIPs = 10.10.0.4/32

[Peer]
PublicKey = 6mcSF7+YJu5OeFqYwq3mO7RhLTeQxHua5q+KNH9ZMS8=
AllowedIPs = 10.10.0.5/32

[Peer]
PublicKey = Ii78RiCHkfY1SA9DSXnXfPgDuvH+FMgEf0h9odM5I20=
AllowedIPs = 10.10.0.6/32

[Peer]
PublicKey = 4MdTN/s/2jVo9j7OkLoq+r7b2wg+5i3Qyj77XcbEFk0=
AllowedIPs = 10.10.0.7/32

[Peer]
PublicKey = ohXbNt1VQLpGrou1ZwglqyssA7YCltYXwgERJizy7R8=
AllowedIPs = 10.10.0.8/32
