{
 "title": "proxmox",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "ultimo backup ok",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"borg\"} |= `ultimo backup`"
    }
   ]
  },
  {
   "title": "ssh",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"authlog\"} |~ `(?i)invalid|failed|failure`"
    }
   ]
  },
  {
   "title": "nextcloud warning",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=\"nextcloud\"} |= `warning`"
    }
   ]
  },
  {
   "title": "bitcoind",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"bitcoind\"} |= ``"
    }
   ]
  },
  {
   "title": "nextcloud errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=\"nextcloud\"} |= `error|Error|ERROR|Fatal|FATAL|fatal|Exception|exception|fail|Fail|failed|Failed`"
    }
   ]
  },
  {
   "title": "electrs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"electrs\"} |= ``"
    }
   ]
  },
  {
   "title": "disk problem nextcloud",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"syslog\"} |= \"error\" |~ \"(?i)(disk|filesystem|I/O)\""
    }
   ]
  },
  {
   "title": "disk problem knots",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"syslog_knots\"} |= \"error\" |~ \"(?i)(disk|filesystem|I/O)\""
    }
   ]
  },
  {
   "title": "error borg ",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"borg\"} |= `borg error` "
    }
   ]
  }
 ]
}